Added script for automated map saving
D7039E-E7032E/Mapping-Robot pull request #17
Opened 2019-12-09 07:57 UTC by anti002

Command for sending maps will be added when that functionality is done

2019-12-09 07:58 UTC, oscrim approved these changes

2019-12-09 09:11 UTC, oscrim requested changes
Ändra så att den sover i 60s istället

2019-12-10 07:28 UTC, linwil-5 approved these changes

2019-12-10 07:29 UTC, linwil-5 approved these changes

2019-12-13 09:31 UTC, oscrim approved these changes
Very nice!

2019-12-13 09:31 UTC, merged